package za.co.enigma.business.domain.party.entity.relationship;

public enum PartyRelationshipType {

	ORGANIZATION_CONTACT_RELATIONSHIP,
	CUSTOMER_RELATIONSHIP,
	SUPPLIER_RELATIONSHIP,
	PROSPECT_RELATIONSHIP,
	INFORMAL_RELATIONSHIP,
	SHAREHOLDER_RELATIONSHIP,
	SYNDICATOR_RELATIONSHIP,
	EMPLOYMENT
	
}
