package za.co.enigma.business.domain.party.entity.role;

public enum PartyRoleType {

	WORKER_EMPLOYEE,
	WORKER_CONTRACTOR,
	CONTACT,
	SIGNER,
	SHAREHOLDER,
	PROSPECT,
	CUSTOMER_PRIMARY_CUSTOMER,
	CUSTOMER_JOINT_PARTY,
	CO_BORROWER,
	AUTHORIZED_BORROWER,
	NOTARY_PUBLIC,
	TRUSTEE,
	BENEFICIARY,
	GUARANTOR,
	CO_SIGNER,
	OTHER_ROLE,
	FINANCIAL_INSTITUTE,
	REGULATORY_AGENCY,
	EMPLOYER,
	COMPETITOR,
	HOUSEHOLD,
	PARTNER,
	SUPPLIER,
	PARTICIPATING_SYNDICATOR,
	CONTROLLING_SYNDICATOR;
	
	
}
